### ISSUE TITLE
ReferenceError when used in a Next.js environment

### ISSUE THREAD

**Issue by ndimatteo** [klevert-ope/Usehlsvideoplayer#1]
Hey there @klevert-ope!

Was looking into using your hook to setup a custom HLS player, but after installing and importing `Usehlsplayer` in one of my components, I'm getting the following error when loading up my page:
<img width="1030" alt="image" src="https://github.com/klevert-ope/Usehlsvideoplayer/assets/737188/c2658d33-c201-4c36-a9e2-fc949a649f36">

Not sure what the deal is, as I followed the fairly simple install instructions (`yarn add hls.js usehlsvideoplayer`). Let me know what you think!

**Comment by klevert-ope** [comment]
Hey I'm looking into it right now.

**Comment by klevert-ope** [comment]
The problem might be that you're attempting to use "require import" instead of the standard "import { Usehlsplayer } from 'usehlsvideoplayer'". Additionally, remember to include TypeScript in the development dependencies to enable autocomplete functionality. Check out the readme for the usage example.

**Comment by ndimatteo** [comment]
Thanks! I am using TypeScript, though not all of my components are `ts`/`tsx` files, and I'm importing it in my component like this:
```
import { Usehlsplayer } from 'usehlsvideoplayer'
```

Ideally I'd be able to import this in standard `js`/`jsx` files, regardless of if you're using typescript internally. Plenty of packages out there written in TS but can be used/imported in non-ts files.

**Comment by klevert-ope** [comment]
Indeed, the hook can be used in files that are not TypeScript (.ts) files. Its primary role in such scenarios is to enhance development through type annotations. I've applied the hook in a project encompassing various file formats, and it has functioned seamlessly. Next, I'll focus on implementing the "require import" feature.
In case there are any issues with file types, please feel free to let me know.
